apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  annotations:
    getambassador.io/rolloutId: 15c3d43f-c5c1-4d3d-be7a-886bf0fecf68
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: web-app
    app.kubernetes.io/part-of: emojivoto
  name: web-app
  namespace: emojivoto
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  strategy:
    canary:
      canaryService: web-app-canary
      stableService: web-app
      steps:
      - setWeight: 10
      - pause:
          duration: 12
      - setWeight: 20
      - pause:
          duration: 12
      - setWeight: 30
      - pause:
          duration: 12
      - setWeight: 40
      - pause:
          duration: 12
      - setWeight: 50
      - pause:
          duration: 12
      - setWeight: 60
      - pause:
          duration: 12
      - setWeight: 70
      - pause:
          duration: 12
      - setWeight: 80
      - pause:
          duration: 12
      - setWeight: 90
      - pause:
          duration: 12
      - setWeight: 100
      - pause:
          duration: 12
      trafficRouting:
        ambassador:
          mappings:
          - web-app
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: web-app
        revision: 2021-07-29.01
    spec:
      containers:
      - env:
        - name: WEB_PORT
          value: "80"
        - name: INDEX_BUNDLE
          value: dist/index_bundle.js
        image: datawire/emojivoto-web-app:v12
        imagePullPolicy: Always
        name: web-app
        ports:
        - containerPort: 80
          name: http
        resources:
          requests:
            cpu: 100m
      serviceAccountName: web-app
status:
  blueGreen: {}
  canary: {}
